spring:
  application:
    name: spring-boot-mongodb
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: '123456'
      authentication-database: admin
      database: mongo_demo

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

data:
  mongo:
    user: admin
    password: 123456
    ssl: false
    authSource: admin
    database: mongo_demo
    address:
      - host: localhost
        port: 27017
